### ISSUE TITLE
error: declarations in AES.h 

### ISSUE THREAD

**Issue by venkyyalagala** [sglvladi/meshquitto#6]
https://github.com/sglvladi/meshquitto/blob/c696fc4ede22d8e7552b3d4a94ea34e4ec54d10c/meshquitto_node/meshquitto_node.ino#L157

Arduino: 1.8.2 (Windows 7), Board: "WeMos D1 R2 & mini, 80 MHz, 4M (1M SPIFFS), v2 Prebuilt (MSS=536), Disabled, None, 921600"

D:\2019\mesh_esp8266\mesh_gateway__node_combo\node_originalcode\node_originalcode\node_originalcode.ino: In function 'String AES_encrypt(String, String)':

node_originalcode:157: error: 'class AES' has no member named 'printToHEXString'

   String cipher = aes.printToHEXString(cipher_buf, cipher_length);

                       ^

D:\2019\mesh_esp8266\mesh_gateway__node_combo\node_originalcode\node_originalcode\node_originalcode.ino: In function 'String AES_decrypt(String, String)':

node_originalcode:206: error: 'class AES' has no member named 'printToString'

   String plain = aes.printToString(plain_buf, plain_size);

                      ^

exit status 1
'class AES' has no member named 'printToHEXString'

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

problem with the meshquitto node program please help to resolve it

**Comment by sglvladi** [comment]
@venkyyalagala It looks like you may have a different version of the AES library.

Could you try using [my fork](https://github.com/sglvladi/AES)? I defined some helper string processing functions in there (see [here](https://github.com/sglvladi/AES/blob/63bcca1a93ac938ea5343357f90bb41bb9d0de49/AES.cpp#L609)).

Let me know how it goes.

**Comment by sglvladi** [comment]
Closing as there has not been any activity in the last 3 months.
